CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  realname VARCHAR(100),
  username VARCHAR(40) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  language VARCHAR(50),
  date_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
